options:
  logging: CLOUD_LOGGING_ONLY

steps:
   # Step 2: Initialize Terraform
  - name: 'hashicorp/terraform'
    args: ['init']

# Step 3: Initialize Terraform
  - name: 'hashicorp/terraform'
    args: ['plan']

  # Step 4: Apply Terraform configuration
  - name: 'hashicorp/terraform'
    args: ['apply', '-auto-approve']
