options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # using codebuild internal cmd to build image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'samweb-app:v1', '.']
  # step 2
  # to do SAST in build image 
  - name: 'aquasec/trivy:latest'
    args: ['image', '--severity', 'HIGH,CRITICAL','--format','json','--output','/tmp/samscan.json', 'samweb-app:v1']
  # step 3
  # create container ss ss
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '-itd', '--name', 'somning11',
     '-p', '1011:80', '--rm', 'samweb-app:v1'
     ]
