options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # using codebuild internal cmd to build image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'samweb-app:v1', '.']
  # step 2
  # to do SAST in build image 
  - name: 'aquasec/trivy:latest'
    args: ['image', '--severity', 'HIGH,CRITICAL','--format','json','--output','/workspace/samscan.json','--exit-code','0', 'samweb-app:v1']
  
  #step 3
  - name: 'google/cloud-sdk'
    args: ['gsutil','cp','/workspace/samscan.json','gs://vodafone-trivy-scan-results/containers/']

    # step 4
  # create container ss ss
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '-itd', '--name', 'somning11',
     '-p', '1011:80', '--rm', 'samweb-app:v1'
     ]

     # step 5 app running status
  - name: 'google/cloud-sdk'
    args: 
      - 'c'
      - |
        curl http://localhost:1011/health.html
