apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: somning-app-deploy
  name: somning-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: somning-app-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: somning-app-deploy
    spec:
      containers:
      - image: asia-docker.pkg.dev/vodafone-devsecops/vodafone-webapp-images/samweb-app:v1
        name: nginx
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources: {}
status: {}